version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  version: 2
  deploy:
    jobs:
      - say-hello
    filters:
      branches:
        only:
          - master
